version: '3.8'
services:
  db:
    # Postgresは12以降が推奨とのこと
    image: postgres:13
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${SQL_USERNAME}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    networks:
      - my-app-network
    logging:
      driver: none
    restart: always

volumes:
  postgres_data:

networks:
  my-app-network:
